# Change these first
owner: kongying-tavern # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Genshin Map
    url: https://yuanshen.site
  - name: Genshin Map v3
    url: https://v3.yuanshen.site
  - name: Genshin Map Dadian
    url: https://dadian.yuanshen.site
  - name: Genshin Map Tiles
    url: https://tiles.yuanshen.site
  - name: Genshin Map Admin
    url: http://admin.yuanshen.site
  - name: Genshin Map Download
    url: https://download.yuanshen.site
  - name: Geenshin Map Assets
    url: https://assets.yuanshen.site/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Kongying Tavern Upptime"
  introMessage: "https://yuanshen.site"
  navbar:
    - title: Status
      href: /
    - title: Sponsor
      href: https://yuanshen.site/docs/support-us.html
    - title: Feedback
      href: https://support.qq.com/products/321980/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
